apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: spf-cluster

servers: 1
agents: 2

kubeAPI:
  host: "10.120.59.70"
  hostIP: "10.120.59.70"
  hostPort: "6443"

options:
  k3d:
    wait: true
    timeout: "120s"

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

  k3s:
    extraArgs:
      - arg: "--tls-san=10.120.59.70"
        nodeFilters:
          - server:*

      # Optional: disable Traefik if you do not need default ingress
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*