apiVersion: v1
kind: Namespace
metadata:
  name: spf-app-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spf-server-dep
  namespace: spf-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spf-server
  template:
    metadata:
      labels:
        app: spf-server
    spec:
      containers:
        - name: spf-server
          image: rishicse24/spf-server:v_0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: spf-server-svc
  namespace: spf-app-ns
spec:
  type: LoadBalancer
  loadBalancerIP: 10.120.59.70
  selector:
    app: spf-server
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000